### ISSUE TITLE
Add support for extending and not replacing the include_dir

### ISSUE THREAD

**Issue by akien-mga** [DavidKinder/Inform6#10]
Hi there,

First of all please tell me if it would have been better to file a report on I7's Mantis instead of here; I chose here as I find GitHub more convenient and it's very-specific to the compiler.

I just packaged the I6 compiler for the Mageia Linux distro based on [Ben Finney's Debian packaging](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805704). We both compile I6 with ``-DInclude_Directory="\"/usr/share/inform6/library\""``, which works great.

So I6 will look by default in this system-wide path for the libraries. Now, when I want to build a project that uses a custom library, I would like to have the possibility to define an additional path for library lookup using a command line switch. There is already ``+include_path=<path>`` (and ``+<path>``), but it overrides the system-defined one.

See e.g.:
```
$ ls
katabasis.inf
scenic5sens.h

$ inform -v8 +Language_name=French katabasis.inf katabasis.z8
Inform 6.33 for Linux (10th May 2014)
[Compil� avec la version 2.3 de la biblioth�que francophone.]
line 795: Fatal error: Couldn't open source file "/usr/share/inform6/library/scenic5sens.h"

$ inform -v8 +Language_name=French +include_path=./ katabasis.inf katabasis.z8
Inform 6.33 for Linux (10th May 2014)
line 11: Fatal error: Couldn't open source file "./Parser.h"
```

The only solution is to specify both the system path and the custom path in the switch, which is tiresome:
```
$ inform -v8 +Language_name=French +include_path=/usr/share/inform6/library/,./ katabasis.inf katabasis.z8
Inform 6.33 for Linux (10th May 2014)
[Compil� avec la version 2.3 de la biblioth�que francophone.]
Compiling Scenic.h
```

------------------

To fix this, there could either be a new switch (e.g. ``+include_path_add=``) that only extends the path instead of replacing it (if the possibility to fully override the system-defined path should be kept). Another possibility would be to support an assignment like ``+=`` instead of ``=``, e.g. ``+include_path+=./``.

**Comment by erkyrath** [comment]
Yes, it is better to file this sort of thing at http://inform7.com/mantis/ .

**Comment by erkyrath** [comment]
This seems like a reasonable feature.

It will be marginally easier to implement (and I think easier to read) if the option looks like `++pathname` or `++include_path=pathname`. This could conceivably break somebody's setup if they have a subfolder named `+files` and are doing `inform ++files`, but I think that's perverse enough to ignore. (The workaround would be `inform +./+files`.)

The `+=` idea is no better for breakage (somebody could have a `=files` dir). The `+include_path` idea would require parsing word-length `-` options, which there is currently no code to do.

**Comment by akien-mga** [comment]
> Yes, it is better to file this sort of thing at http://inform7.com/mantis/ .

Should I move it over there, or do we continue to discuss it here?

I agree that `+=` alone would be weird, not just because someone could have a `=files` folder but because it's not really explicit. I proposed it only as in `+include_path+=`, where `+=` serves as an incrementer and not as a re-assignment. But since `+` and `+include_path=` are currently synonyms, it wouldn't work that well indeed.

I think the `++`/`++include_path=` syntax is nice.

**Comment by erkyrath** [comment]
Yeah, copy this discussion there. David may have further comments.

**Comment by akien-mga** [comment]
Moved to http://inform7.com/mantis/view.php?id=1916
