### ISSUE TITLE
GCC 6 reports “implicit declaration of function ‘getpid’”

### ISSUE THREAD

**Issue by bignose-debian** [DavidKinder/Inform6#11]
When compiling with GCC version 6, the compiler warns about an implicit function declaration:

```
$ gcc --version
gcc (Debian 6.1.1-11) 6.1.1 20160802
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc -DUNIX64 -c -o inform.o inform.c
In file included from inform.c:11:0:
header.h: In function ‘unique_task_id’:
header.h:457:19: warning: implicit declaration of function ‘getpid’ [-Wimplicit-function-declaration]
 {   return (int32)getpid();
                   ^~~~~~
```

This indicates an existing problem (functions should be explicitly declared) that was not being reported by some earlier compiler versions.

**Comment by erkyrath** [comment]
This should already be fixed in my development tree (https://github.com/erkyrath/inform6). David has not yet merged this change.

See http://inform7.com/mantis/view.php?id=1937 for more discussion. In particular, -DUNIX64 is changing to just -DUNIX .

**Comment by bignose-debian** [comment]
@DavidKinder, is this closed because there's a commit which fixes it? Which commit?

**Comment by erkyrath** [comment]
https://github.com/DavidKinder/Inform6/commit/55ec5ec51d34572fedea428527f3ee5c7f2a72cc

**Comment by erkyrath** [comment]
Specifically the added "#include <unistd.h>" line.
