### ISSUE TITLE
Declare an individual property

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#126]
When writing a library extension, you often need to add a property. Since common properties are in limited supply, you typically want to let the user decide if it should be a common property or an individual property. So, you leave it to the user to either declare it or not declare it. This has the problem that if the user includes the extension, without actually using the property, they get a compilation error. This is ugly and unnecessary. What I would like is a way for extension code to declare an individual property. Something like:

#Ifndef cuddliness;
Property individual cuddliness;
#Endif;

If the game author has already declared this as a common property, nothing happens. If they haven't, it's declared as an individual property.

(In Glulx, which IIRC doesn't have individual properties, this would just define a normal property)

**Comment by erkyrath** [comment]
There is already a way to declare an individual property, using dummy object.

    Object dummy with cuddliness;

I suppose this is an undesirable waste for V3 games, though. The suggestion makes sense. But I think we need to be careful that

    Property individual;

...remains a valid declaration of a common property. (Might as well support "Property long;" and "Property additive;" too! Those are currently impossible to declare.)

> (In Glulx, which IIRC doesn't have individual properties, this would just define a normal property)

The Glulx veneer distinguishes between common and individual properties, and you declare them the same way on both VMs.

**Comment by fredrikr** [comment]
Indeed, this is more important for z3 games.

The syntax doesn't *have to* look like that, but I think it makes the most sense to either use:
```
Property individual cuddliness;
```
or
```
Property cuddliness individual;
```
