### ISSUE TITLE
Addition to I6 addendum

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#132]
When explaining that you can work around that obj.prop() doesn't work in Z3, one should also mention that the suggested workaround means `self` won't be set correctly.

https://www.inform-fiction.org/manual/I6-Addendum.html#z-machine-v34-limitations

**Comment by erkyrath** [comment]
I've updated the example to say:

```
	@push self;
	self = obj;
	addr = obj.prop;
	addr();
	@pull self;

[[The lines dealing with `self` may be omitted if the property routine does not rely on `self`.]]
```

Addendum document issues can go in https://github.com/iftechfoundation/ifarchive-if-specs , by the way.
