### ISSUE TITLE
Property count and error messages

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#137]
Compile this program with -v3s:

```
Property p1;
Property p2;
Property p3;
Property p4;
Property p5;
Property p6;
Property p7;
Property p8;
Property p9;
Property p10;
Property p11;
Property p12;
Property p13;
Property p14;
Property p15;
Property p16;
Property p17;
Property p18;
Property p19;
Property p20;
Property p21;
Property p22;
Property p23;
Property p24;
Property p25;
Property p26;
Property p27;
Property p28;

! Property p29 alias p1;

Array buffer -> 100;
Array parse -> 100;

[main x;
	buffer->0 = 20;
	parse->0 = 10;
	print "Property p1 has #", p1, ".^";
	print "Property p28 has #", p28, ".^";
	@sread buffer parse;
];
```
Several problems can be observed here:

(A) The compiler reports that we have created 30 common properties, and the maximum possible is 30. The Z-machine maximum is in fact 31. We have defined 28. "name" is defined automatically, so that's 29. It would make sense that the compiler said we have defined 28 out of 28 possible, or maybe 29 out of 29 possible (including "name" in the calculation), or even 31 out of 31 possible (including the other "secret" properties). 30 out of 30 possible makes no sense. 

(B) If we uncomment the line that defines property p29, the compilation fails. It works if we move it up to before the line that defines p28. Looks like the compiler gives up because it looks like we want to define a new property, but as this is an alias it should succeed.

(C) When the compilation fails in (B), the error message says "All 30 properties already declared (compile as Advanced game to get an extra 62)". This is not true. You don't get 92 properties in z5.

**Comment by erkyrath** [comment]
The development (unreleased) version has already updated the error message:

> line 30: Error:  All 29 properties already declared (compile as Advanced game to get 32 more)

I didn't update the -s output when I made this change, so yeah, that's inconsistent. That report should show a count one lower (both for the current and maximum).

**Comment by erkyrath** [comment]
The alias question will take more looking, sorry.

**Comment by erkyrath** [comment]
The official property count, by the way, is that Inform skips using property 0. (I don't remember if it's invalid in the Z-machine or if Inform just wants to reserve the value.) It reserves two internal properties (the class inheritance pointer and the individual property table pointer). So that leaves 29 properties available in v3. Then the compiler auto-defines "name", which counts as the first of the 29.

The -s report on a trivial v3 game should therefore say "1 common props (maximum 29)".

**Comment by curiousdannii** [comment]
> @get_prop_len 0 must return 0. This is required by some Infocom games and files generated by old versions of Inform.

This probably prevents property 0 from being used. The other property opcodes look okay, but it's probably just not worth the risk.

**Comment by erkyrath** [comment]
Thanks! Figured it was like that.
