### ISSUE TITLE
Make INDIV_PROP_START a memory setting

### ISSUE THREAD

**Issue by jessepav** [DavidKinder/Inform6#14]
A patch to make INDIV_PROP_START configurable as a memory setting, following Andrew Plotkin's paragraph in his glulx-technical.txt:

> The value of INDIV_PROP_START is currently hardwired to 256, in the
> compiler. It will eventually be made flexible. The veneer and library
> use the constant INDIV_PROP_START, so they can adapt to any value the
> compiler defines.

https://github.com/jessepav/Inform6/commit/2a9cf26c9b2a8e903893d153e0dbf6fce17afb69

**Comment by erkyrath** [comment]
This looks fine.

Did you run into a situation where you needed to set it? I'm sure I haven't thought about that constant in twenty years, but I also haven't ever needed to raise it.

**Comment by jessepav** [comment]
I haven't needed to raise it yet, but I was considering using Inform 6 as a code-generation target and I figured it might be useful at some point. And after reading the glulx-technical I somehow felt an urge to make it configurable, partially to learn my way around the source.

**Comment by DavidKinder** [comment]
Patch merged.
