### ISSUE TITLE
Can't compile a word array or table containing a routine

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#143]
Inform 6.35 doesn't compile:

```
Array global_comments table
	"msg 1"
	[; print "msg 2"; ]
	"msg 3";
```
The error message is:
```
comments.inf(70): Error:  Missing ';' to end the initial array values before "[" or "]"
```

It works fine in a property array.

**Comment by erkyrath** [comment]
Anonymous routines can't be used as general expression values. They can only be used in property declarations.
