### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#144]
This code, compiled with PunyInform v3.2 crashes the compiler. I haven't managed to make an example that crashes the compiler without the library.

```
Constant Story "Crash the compiler";
Constant Headline "^Yada yada.^";
Statusline score;

Include "globals";
Include "puny";

Object BigKitchen "Big Kitchen"
	with
		description "A kitchen.",
	has light;

Array global_comments table
	"msg 2"
	[ x y;
		x = 1 + random(8); y = 1 + random(8);
		print "Suddenly Burt asks you what ", x, " multiplied by ", y, " is.
			~Oh, never mind, it's ", x * y, " right?~^";
	];

[ Initialise;
 	location = BigKitchen;
	"^^";
];
```

**Comment by erkyrath** [comment]
I'm afraid this is very sporadic. I was able to reproduce it once in several tries.

   segfault at: construct_storyfile_z + 14963 (tables.c:928)

**Comment by erkyrath** [comment]
Best I can tell, the error case in array.c exited make_global() (in the array case) before finish_array() was called. This left some uninitialized data in memory, which later messed up the Z-machine image as it was constructed.

I've removed that return call. You now get more error messages, but I think it prevents the crash.
