### ISSUE TITLE
Option to omit last byte in dictionary words

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#146]
Every dictionary word in Z-code has four or six bytes to store the word string and then three bytes of data. The last of these data bytes hasn't been used since ancient times in the standard library (grammar version 1) and never in PunyInform, but is always included by the compiler. This wastes ~500-2000 bytes in a typical game. Could we have a commandline switch to skip it?

**Comment by erkyrath** [comment]
It's a reasonable request, but there are some complications.

What do we call it? `$SMALL_ZCODE_DICT` maybe.

This setting will be Z-code only. (In theory a Glulx game could use it, but I don't see much value. Anyhow, the Glulx I6 library code currently has `entrylen = DICT_WORD_SIZE + 7` hard-coded into it, and it's a nuisance to change that.)

Any game can use the `Dictionary 'word' val1 val3` directive to set byte 3 for any word. The compiler will have to generate a warning if the game does this while also trying to use the setting.

What if the game tries to do `word->#dict_par3` when using the setting? I suppose the compiler could generate a warning for this case as well.

The compiler always defines a `DICT_ENTRY_BYTES` constant. Currently this is always 7 or 9 for Z-code, but Z-code game and library code has little reason to use it. But we can adjust it appropriately anyhow.

**Comment by erkyrath** [comment]
In the interests of flexibility, would we also want to be able to *enlarge* the dict entry size? But I don't particularly want to extend the `Dictionary` directive to support an arbitrary number of values. That would be ugly.

**Comment by fredrikr** [comment]
I'm thinking #dict_par3 should be undefined if this option is used.

Doesn't seem like there's much demand for enlarging the dict entry size.

**Comment by fredrikr** [comment]
Very happy to see this happen!
