### ISSUE TITLE
Where to find compatible library for Inform 6.33 ?

### ISSUE THREAD

**Issue by mstram** [DavidKinder/Inform6#15]
Hi David,

What / where is the compatible library for Inform 6.33 ?

I've been trying to use this one,  (the only one I've found), but it throws all kind of errors.

http://www.ifarchive.org/if-archive/infocom/compilers/inform6/library/inform_library-6.12.1.zip

Mike

**Comment by erkyrath** [comment]
The 6/11 release (under http://www.ifarchive.org/if-archive/infocom/compilers/inform6/library/old/) is the last release that shipped with Inform. The 6/12 line has been updated as a separate project (https://gitlab.com/DavidGriffith/inform6lib/tags). I haven't been following the bugs or changelist, so you'll have to ask DavidGriffith about problems.
