### ISSUE TITLE
Preprocessor functionality

### ISSUE THREAD

**Issue by DavidGriffith** [DavidKinder/Inform6#150]
What do you all think of the idea of a preprocessor for Inform 6?  The solution to #130, while effective, is clunky.  What I'm thinking of is to detect when a `grammar` property tries to return a negated verb and insert a `parser_one = true;` before that.

**Comment by erkyrath** [comment]
You're welcome to write one, but there are plenty of off-the-shelf text preprocessors out there. And I don't think a preprocessor is going to handle that case reliably.

I don't think it makes sense to include such a thing in the standard toolchain, anyhow.

**Comment by DavidKinder** [comment]
Closing this as there doesn't seem to be much enthusiasm for implementing anything like this inside the Inform codebase.
