### ISSUE TITLE
Combine READMEs?

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Inform6#151]
Otisdog [comments][thread] that if you download the distributed inform636_source.zip file, you get an abbreviated readme.txt which just tells you to visit http://www.ifarchive.org/indexes/if-archiveXinfocomXcompilersXinform6.html. That leads you to ReleaseNotes.html. However, it *doesn't* lead you to the short history-of-Inform and how-to-compile sections which are in README.md. Those can only be found on Github.

[thread]: https://intfiction.org/t/inform-6-36/54279/14

We could drop the existing readme.txt, merge its info into the start of README.md, and then include that in the source package.

(While I'm at it: the Archive URL can be given as https://ifarchive.org/indexes/if-archive/infocom/compilers/inform6/ these days.)

**Comment by DavidKinder** [comment]
Fixed by 8e8f80ad303e9da57e9091ab8722b6fb17c8bbbb.
