### ISSUE TITLE
Include up-to-date Unix manual page in source release

### ISSUE THREAD

**Issue by bignose-debian** [DavidKinder/Inform6#157]
The source code from this repository results in the `inform` command, but does not include an up-to-date Unix manual page corresponding to that command.

@DavidGriffith maintains a manual page appropriate for this command; it is in the repository at https://gitlab.com/DavidGriffith/inform6unix/-/blob/master/inform.1

Please consolidate maintenance of that manual page source code, into this same source code project, so the two correspond, and get released as part of the same source package.

**Comment by DavidKinder** [comment]
I do not intend to add OS-specific documentation formats to this Inform 6 repository. David G's "Inform 6 for Unix" package is the correct place for such things.

**Comment by bignose-debian** [comment]
On 25-Feb-2022, David Kinder wrote:

> I do not intend to add OS-specific documentation formats to this
> Inform 6 repository.

Thank you for the prompt and clear response.

-- 
 \     “Some mornings, it's just not worth chewing through the leather |
  `\                                             straps.” —Emo Philips |
_o__)                                                                  |
Ben Finney ***@***.***>
