### ISSUE TITLE
Port to Julia?

### ISSUE THREAD

**Issue by bramtayl** [DavidKinder/Inform6#16]
I was looking at this and thinking it might be nice to port to Julia. I could do the work but I'd probably have to ask a lot of questions. Is that something people would be interested in?

**Comment by erkyrath** [comment]
You are referring to Julia the language? (It's not a language I was aware of.)

You're welcome to do it as an exercise, but I don't think people would specifically be interested in it. Inform 6 is already in portable C; it's been easy to build on many platforms; and there hasn't been much call for a more efficient implementation.

**Comment by erkyrath** [comment]
A Z-machine or Glulx *interpreter* written in Julia might be more interesting. There are plenty of interpreters out there, but that's an area where efficiency *can* be important.

**Comment by bramtayl** [comment]
I wouldn't do it for speed (Julia is still a bit slower than C) but for readability/ease of maintenance. I'd be happy to work on a Z-machine or Glulx interpreter instead, too, though.
