### ISSUE TITLE
Double-precision support

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Inform6#177]
See discussion: https://intfiction.org/t/double-precision-math-in-glulx/55876

A double must be stored as *two* Glulx words.  A double literal in I6 will look like `$>+1.0`, `$<+1.0` for the high and low words.

We will add I6 constants DOUBLE_HI_NAN, DOUBLE_LO_NAN, DOUBLE_HI_NINFINITY, DOUBLE_LO_NINFINITY, DOUBLE_HI_INFINITY, DOUBLE_LO_INFINITY.

Let's try using the Github task list system! Yeah, I'm including Glulxe work here so it's all in one place.

I6:
- [x] opcodes in asm.c and lexer.c
- [x] gestulx_Double
- [x] parsing of double literals
- [x] I6 symbols for double infinity and NaN
- [x] doubleconsttest
- [x] dpull, dpush macros (not opcodes)

Spec:
- [x] document double format
- [x] document all double opcodes
- [x] gestulx_Double
- [x] document whatever that Inf-casting inconsistency was

Interpreter:
- [x] gestalt
- [x] double encode/decode
- [x] operand formats
- [x] all opcodes
- [x] glulxercise test cases
- [x] test with DOUBLE_SUPPORT and FLOAT_SUPPORT turned off

I6 ref addendum:
- [x] document new literal syntax
- [x] document new I6 constants
- [x] document macros

**Comment by DavidKinder** [comment]
Sorry, I edited this with an inadvertent click. I think I've reverted the effect of this.

**Comment by erkyrath** [comment]
Somewhat shockingly, I've gotten this all to work, with implementations in glulxe and quixe.

I'll start working up a round of releases.
