### ISSUE TITLE
<<X Y Z>> no longer works in z3

### ISSUE THREAD

**Issue by DavidKinder** [DavidKinder/Inform6#18]
_From Johan Berntsson:_

I have discovered a bug in Inform6 and I want to ask if you can make sure that it is being fixed in a future upgrade.

I and some friends are making a new standard library for small computers (think Commodore 64) which is called PunyInform: https://github.com/johanberntsson/PunyInform We are testing this on both z3 and z5, while the Inform stdlib no longer works on z3. What I have discovered is that <<X Y Z>> no longer works in z3. It doesn't return from the function as it is supposed to (the implicit rtrue isn't generated).

The problem is line 173 on states.c:
`assemblez_4(call_zc, AO, AO2, AO3, AO4);`
should instead be:
`assemblez_4_to(call_zc, AO, AO2, AO3, AO4, temp_var1);`

Since the temp_var1 is missing the next instruction (the rtrue) will be assumed to be a global variable location instead, so the rtrue is never executed, causing the problem (but only in z1-z3 of course; z5 etc works). I have recompiled the Inform compiler and confirmed that this change solves the problem.

I have attached the fixed and working states.c. Can you make sure that the fix finds its way into the official repository?
[states.c.txt](https://github.com/DavidKinder/Inform6/files/4597606/states.c.txt)

**Comment by erkyrath** [comment]
I've verified this fix. Simple test case:

```
Constant Story "Minimal";
Constant Headline "^Headline.^";

[ Main;
	print "Hello.^";
	<Blorb 1 2>;
	print "More.^";
	<<Frotz 3 4>>;
	print "Should not reach here.^";
];

[ BlorbSub; ];
[ FrotzSub; ];
```

**Comment by erkyrath** [comment]
https://github.com/erkyrath/inform6/commit/78d9953ed61b7d15cb30e25ce907315089b74cc3

**Comment by erkyrath** [comment]
I rejiggered my github repo so it's a fork of yours, so now I can make PRs and everything. `:)`
