### ISSUE TITLE
Move debugging file format details to Inform 6 Reference Addendum

### ISSUE THREAD

**Issue by DavidKinder** [DavidKinder/Inform6#183]
The Inform 6 repository currently contains a description of the new debugging file format at [DebugFileFormat.txt](https://github.com/DavidKinder/Inform6/blob/master/DebugFileFormat.txt). This information should be moved to a section in the [Inform 6 Reference Addendum](https://ifarchive.org/if-archive/infocom/compilers/inform6/manuals/I6-Addendum.html).

**Comment by erkyrath** [comment]
Sure, can do.

**Comment by erkyrath** [comment]
How does this look?

http://inform-fiction.org/manual/I6-Addendum.html#debugformat

I shoved in the file almost verbatim. I only reworded a couple of lines, fixed typos, and updated the opening paragraphs.

(This version of the Reference Addendum says "6.37" but I think it's strictly 6.36 right now. I have not yet added the trace option changes.)

**Comment by DavidKinder** [comment]
Thanks, that looks fine.

Commit 7cd126c1d283e521964327dc5212c7bdf4fff5bf removes DebugFileFormat.txt from this repository.
