### ISSUE TITLE
inform6 6.41-r1 linux build failure

### ISSUE THREAD

**Issue by chenrui333** [DavidKinder/Inform6#199]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
  /tmp/inform6-20220807-2280-191tfzb/inform-6.41-r1/inform-6.41 +std std-demos/ruins1.inf std-demos/ruins1.z5
  Inform 6.41 for Unix (22nd July 2022)
  A specified path is longer than 127 characters.
  Makefile:210: recipe for target 'std-demos/ruins1.z5' failed
  make: *** [std-demos/ruins1.z5] Error 1
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/7709329558
relates to Homebrew/homebrew-core#107488

**Comment by DavidKinder** [comment]
The build log suggests that you're building with UNIX defined, which gets a very conservative set of OS-specific definitions, including a maximum path length of 128. If you define LINUX instead, you'll get a much longer path length. See the definitions of UNIX and LINUX in header.h for more details.
