### ISSUE TITLE
there's no makefile

### ISSUE THREAD

**Issue by faried** [DavidKinder/Inform6#2]
This isn't a major issue, but the repo doesn't have a makefile.  I've hacked one up and placed it [here](https://gist.github.com/1187533).

**Comment by akien-mga** [comment]
What was the reason for closing this issue? There is still no makefile, and no statement from @DavidKinder that it would not be needed.

If there is a concern about portability as expressed by @erkyrath, you could have one makefile per platform like many projects do: ``makefile.win``, ``makefile.bsd``, ``makefile.linux``.

And if there's really too many platforms that can't use a pre-defined makefile, well those platforms can continue building the source manually. But no makefile and no instructions on how to compile is not really distribution-friendly.

**Comment by BroadcastGames** [comment]
I suggest a folder of "sample makefiles" and a readme to go along with each one? Or even a link to a topic on the forums to have people share and ask for help on them?
