### ISSUE TITLE
Label vs constant conflict

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#200]
If you try to compile this program with Inform v6.41, you get an error because the label `failed` has the same name as a constant. Also, you get an error because you're trying to use a label (test) as a value. Since the compiler knows a label can't be used as a value, it shouldn't have a problem with a label name being the same as a constant?

Curiously, if you move `print test;` to before the label `test`, instead of a message saying a label can't be used as a value, you get a quite different error message: No such constant as "test"

Also, you get a warning that a statement can't be reached, even though it's always reached.

```
Constant FAILED = 5;

[main;
	@jump failed;

.failed;
	print "Complete and utter failure.^";
.test;
	print test;
	return FAILED;
];
```

Compiler output:

```
labelfail.inf(6): Error:  Expected label name but found failed
> .failed
labelfail.inf(6): Error:  Expected expression with side-effects but found <constant>
> .failed;
labelfail.inf(7): Warning:  This statement can never be reached
>  print "Complete and utter failure.^"
labelfail.inf(8): Error:  Label name used as value: "test"
>  print test
Compiled with 3 errors and 1 warning (no output)
```

**Comment by erkyrath** [comment]
Notes: this behavior is the same in older releases. (I tested back to 6.34.)

> Also, you get a warning that a statement can't be reached, even though it's always reached.

The warning only appears because the jump statement didn't compile.

**Comment by erkyrath** [comment]
> Since the compiler knows a label can't be used as a value, it shouldn't have a problem with a label name being the same as a constant?

The compiler can't keep track of two meanings for one symbol (within a single function). So "failed" can either be parsed as a constant or label. If you try to use it both ways, one of them has to be an error.

The buggy case is this:

```
Constant FAILED = 5;
[ Main;
	@jump failed;
	return FAILED;
];
```

This compiles to an invalid game file! I'm not sure what the jump opcode winds up containing, but Frotz throws an "illegal opcode" error. So that's bad.

**Comment by erkyrath** [comment]
Although, now that I think about it, assembly code is supposed to be a "you know what you're doing" area. If the author wants to write `@jump` with a constant offset, it's really not our job to stop them.

**Comment by fredrikr** [comment]
The compiler does allow local symbols to override global symbols, e.g.

```
Object hat "hat";

[MyRoutine hat;
  print hat;
];
```

A label is local to the routine it's defined in. Shouldn't the local meaning of the symbol override the global meaning here as well?

This would make it easier to write library code that doesn't come in conflict with stuff the game designer wants to define. Also, I think it would make sense.

**Comment by erkyrath** [comment]
> A label is local to the routine it's defined in. Shouldn't the local meaning of the symbol override the global meaning here as well?

Local variables are declared up front in the routine. Labels aren't. I think there'd be a ton of ambiguity trying to figure out conflicts.

The benefit of this idea seems low compared to the amount of work it would take to make it work consistently.

**Comment by DFillmore** [comment]
> The buggy case is this:
> 
> ```
> Constant FAILED = 5;
> [ Main;
> 	@jump failed;
> 	return FAILED;
> ];
> ```

Inform will compile with absolutely anything after @jump.

```
[ Main;
	@jump drfkfrgkjdj;
];
```
(where drfkfrgkjdj is not declared anywhere) compiles. The location being jumped to appears to be the start of the (non-existent) Main__ routine. That is, one byte before the location of the first instruction as indicated in the header.

**Comment by erkyrath** [comment]
Oh, good catch. 

In Glulx you get errors. (Starting with "Branch opcode must have '?' label", but if you add the `?`, you then get "Routine contains no such label".) But in Z-code, no error.

This isn't a recent bug, either -- goes back to 6.31 at least.

**Comment by erkyrath** [comment]
It gets sillier. This doesn't compile in Z-code!

```
[ Main val;
	.loop;
	val++;
	if (val < 3) {
		@jump loop;
	}
];
```

Without the `@` sign, it's fine. But if you try to use the assembly form of `@jump` for a backwards jump, you get an error:

> Error:  Label name used as value: "loop"

I think this stems from the inconsistency of parsing `@jump foo` as a regular argument (no question mark).

I can probably special-case it, sigh.

**Comment by erkyrath** [comment]
I have a fix, although I haven't written a full set of test cases yet.

With this, `@jump drfkfrgkjdj;` gives:

> Error: Routine contains no such label as "drfkfrgkjdj"

My earlier example:

```
Constant FAILED = 5;
[ Main;
	@jump failed;
	return FAILED;
];
```

> Error: Expected label name but found failed
