### ISSUE TITLE
Error is reported in wrong file + line

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#201]
I tried but unfortunately failed to make a minimal example here.

This is using Inform 6.41 under Windows 10.

The included archive includes my work copy of PunyInfom and a sample game. If you compile the game, the compiler reports an error on line 1602 of grammar.inf, but that's a lie. The error is in fact on line 593 of puny.h

The game includes puny.h, which in turn includes grammar.h, and it seems the compiler fails to understand that grammar.h has ended and it's back in puny.h again.

Compile with:
```
inform6 listtog.inf
```

[include_error.zip](https://github.com/DavidKinder/Inform6/files/9439797/include_error.zip)

**Comment by erkyrath** [comment]
Error message:

> "grammar.h", line 1602: Error:  No such constant as "_obj"

(This was slightly confounded by testing DOS line endings on a Mac, but I edited the source files to have regular line endings and got this error.)

**Comment by erkyrath** [comment]
Managed to create a minimal example:

```
[ Main;
	Look();
	ShowObj();
];

[ Look _obj;

#Ifndef NO_SUCH_SYMBOL;
	if (_obj) return;
#Endif;
	_obj = 1;
];


[ ShowObj;
	return _obj;
];
```

> line 10: Error:  No such constant as "_obj"

(Should be line 16, not 10.)

The trigger seems to be the symbol `_obj` appearing after the `#Endif;` in exactly this pattern. The contents of the `#Ifndef` section matter to some extent I haven't worked out. If you change the conditional to `#Ifdef`, or change the body to anything other than an `if` statement, the bug doesn't happen.

I suspect this has to do with how the lexer parses symbols ahead. The global `dont_enter_into_symbol_table` is sometimes true, sometimes false as we parse. But the put_token_back() function cannot undo entering a symbol into the table. So we sometimes wind up with a spurious global symbol.

(See comment on lexical_context() in lexer.c. Also see https://github.com/DavidKinder/Inform6/issues/163 .)

**Comment by erkyrath** [comment]
I dug a little deeper and must correct myself: the significant flag is `local_variables.enabled`. For some reason in the bad case that gets turned off. 

Hm. I suspect this comment:

```
        /* Restore all the lexer flags. (We are squashing several of them
           into a single save variable, which I think is safe because that's
           what CKnight did.)
        */
```

I'll bet you a dollar it's not as safe as cknight thought.

**Comment by erkyrath** [comment]
It's worth fixing the routine that comment occurs in, but it is not in fact the source of the bug. Oh well.
