### ISSUE TITLE
Option to skip the symbol names table

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Inform6#204]
The generated game file includes a "symbol names table" segment (see `identifier_names_offset` in tables.c). This refers to compiled strings containing the names of all properties, attributes, fake actions, and arrays.

This information is *in general* used only for debug library code and debug veneer error messages. It would be nice to have a (opt-in) compiler setting to strip it all out. (Both the table segment and the compiled strings.)

This would affect the following system constants: #identifiers_table, #action_names_array, #array_names_array, #fake_action_names_array, #attribute_names_array, #global_names_array, #routine_names_array, #constant_names_array.

It also affects the Print__PName() veneer function (which uses #identifiers_table) and certainly other code that I haven't tracked down yet. 

We'd have to make sure that any use of those features would produce errors or sensible fallbacks for all combinations of `-D` and `-S`. (And that's not getting into `-G`, which we can probably ignore for the purposes of this feature.) I estimate this task at "large pain in the ass".

**Comment by heasm66** [comment]
I made a first crude attempt.

Changes in the following files:

1. `header.h`; added new setting,  `ZCODE_OMIT_SYMBOL_NAMES`.
```
...
extern int ZCODE_HEADER_EXT_WORDS, ZCODE_HEADER_FLAGS_3;
extern int ZCODE_LESS_DICT_DATA;
extern int ZCODE_OMIT_SYMBOL_NAMES;
...
```
2. `memory.c`; added parsing of command line for new setting.
```
...
int ZCODE_HEADER_FLAGS_3; /* (zcode 1.1) value to place in Flags 3 word */
int ZCODE_LESS_DICT_DATA; /* (zcode) use 2 data bytes per dict word instead of 3 */
int ZCODE_OMIT_SYMBOL_NAMES; /* (zcode) 0: no, 1: yes */
...
static void list_memory_sizes(void)
...
printf("|  %25s = %-7d |\n","WARN_UNUSED_ROUTINES",WARN_UNUSED_ROUTINES);
printf("|  %25s = %-7d |\n","OMIT_UNUSED_ROUTINES",OMIT_UNUSED_ROUTINES);
printf("|  %25s = %-7d |\n","ZCODE_OMIT_SYMBOL_NAMES",ZCODE_OMIT_SYMBOL_NAMES);
...
extern void set_memory_sizes(void)
...
STRIP_UNREACHABLE_LABELS = 1;
TRANSCRIPT_FORMAT = 0;
ZCODE_OMIT_SYMBOL_NAMES = 0;
...
static void explain_parameter(char *command)
...
if (strcmp(command,"SERIAL")==0)
{
    printf(
"  SERIAL, if set, will be used as the six digit serial number written into \n\
the header of the output file.\n");
    return;
}
if (strcmp(command,"ZCODE_OMIT_SYMBOL_NAMES")==0)
{   printf(
"  ZCODE_OMIT_SYMBOL_NAMES, if set to 1, removes symbol names table and data\n\
from the game file. (Z-code only.)\n");
    return;
}

printf("No such memory setting as \"%s\"\n",command);

return;
...
extern void memory_command(char *command)
...
if (strcmp(command,"SERIAL")==0)
{
    if (j >= 0 && j <= 999999)
    {
        sprintf(serial_code_buffer,"%06d",j);
        serial_code_given_in_program = TRUE;
        flag=1;
    }
}
if (strcmp(command,"ZCODE_OMIT_SYMBOL_NAMES")==0)
{
    ZCODE_OMIT_SYMBOL_NAMES=j, flag=1;
    if (ZCODE_OMIT_SYMBOL_NAMES > 1 || ZCODE_OMIT_SYMBOL_NAMES < 0)
        ZCODE_OMIT_SYMBOL_NAMES = 1;
}
...
```
3. tables.c; the actual work. Only allow the removing the table if not `-G` or `-D` or `-S` or `-X`. Omit writing the symbol names to the strings and setting the tables to a table with 0 length.
```
...
static void construct_storyfile_z(void)
...
array_name_strings =
    my_calloc(sizeof(int32),
        no_symbols,
        "array name strings");

if (ZCODE_OMIT_SYMBOL_NAMES && 
    (glulx_mode || define_DEBUG_switch || 
     runtime_error_checking_switch || define_INFIX_switch)) {
    error("ZCODE_LESS_DICT_DATA cannot be used with Glulx, DEBUG, INFIX or strict error checking.");
}
if (!ZCODE_OMIT_SYMBOL_NAMES)			
   write_the_identifier_names();

/*  We now know how large the buffer to hold our construction has to be  */

zmachine_paged_memory = my_malloc(rough_size_of_paged_memory_z(),
    "output buffer");
...
/*  ------------------- Table of Identifier Names ---------------------- */

identifier_names_offset = mark;

if (!ZCODE_OMIT_SYMBOL_NAMES)
{   p[mark++] = no_individual_properties/256;
...
} else
{   attribute_names_offset = mark;
    action_names_offset = mark;
    array_names_offset = mark;
    global_names_offset = mark;
    routine_names_offset = mark;
    constant_names_offset = mark;
    p[mark++] = 0;
    p[mark++] = 0;
}
routine_flags_array_offset = mark;
...
```

I havn't seen any side effects yet and, as far as I can see, the `Print__PName` routine will print `<number [prop-number]>` when the name is not in the table.

**Comment by heasm66** [comment]
Some more info...

I looked through all veneer-routines (for zcode) and made alternate versions for the ones that are not used exclusivly by the `STRICT_MODE`.

These alternate versions are aimed at a final production release and are stripped of all printing of run-time messages and all calls to `RT__Err` are removed. During this process I didn't find any use of the symbol_names_table, except for `Print__PName` mentioned above.

Attached are the alternate replacement version of veneer, to be included in project, and the assembly output I used to compare before/after so I didn't mangled them.
  
[veneer_release.txt](https://github.com/DavidKinder/Inform6/files/10811913/veneer_release.txt)
[veneer_org.txt](https://github.com/DavidKinder/Inform6/files/10811909/veneer_org.txt)
[veneer_new.txt](https://github.com/DavidKinder/Inform6/files/10811908/veneer_new.txt)

**Comment by erkyrath** [comment]
Okay, whoa. Removing all the error messages from the veneer code is a *completely* separate proposal. `:)`

**Comment by heasm66** [comment]
Oooh no, that's not a proposal. If one would like to do that it's better to include the replacements in your project. I was just looking for side-effects of removing the  symbol_names_table.
