### ISSUE TITLE
Adjust v6.34 tag?

### ISSUE THREAD

**Issue by DavidGriffith** [DavidKinder/Inform6#23]
Given fixing the release notes typo in f064fea255a9a87e70d46d08143c090823a52c0c, should the tag for v6.34 be moved to point there?

**Comment by curiousdannii** [comment]
No, tags should remain as they are, with any bugs or other flaws.

**Comment by erkyrath** [comment]
If David decided to build a new source package with the updated release note and upload that -- which I don't recommend -- then... you still wouldn't want to change the tag. Create a new "v6.34_1" tag, I guess, in that case.

**Comment by DavidKinder** [comment]
I'm with Dannii and Andrew on this one: once a tag is in place, it stays, flaws and all.
