### ISSUE TITLE
Failure to find value of replaced procedure

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#230]
If we first refer to a procedure, then issue a replace directive, then give the first definition, then *in a system file* give the second definition, the compiler gives an error saying the first line where we refer to the value can't be compiled since the value doesn't exist.

Simplest example:

```
System_file;

Global my_foo = foo;

Replace foo;

[ foo;
	"foo 1";
];

[ foo;
	"foo 2";
];
		
[main;
	my_foo();
];
```

If you remove `System_file;` it works. If the base file lacks `System_file;` but you put the second definition of foo in a file of its own, and mark this file with System_file, you get the same error.

I found this in v6.41.

**Comment by erkyrath** [comment]
Using a Global statement like that to capture a replaced function is not supported. I'm surprised it works in any case.

If you want to replace a function but still refer to the original version, do:

```
Replace foo my_foo;
```

The compiler assumes that the system file (or "original" version of the function) will appear *first*, and the replacement ("new" version) will be defined after that. If you put them in the other order, you'll get apparently backwards results.

You could maybe argue that a System_file version of the function should count as "original" no matter where it appears, but at this point the entire Replace feature is a hairball of good intentions and I think it would be a mistake to bother it.

**Comment by erkyrath** [comment]
If you're not trying to capture the original version of the function, but just have a global variable initialized to the function address, then put the Replace directive first.

**Comment by fredrikr** [comment]
I was expecting to get the value of the second version of the function, and this works, unless the second version is defined in a file which contains the System_file directive.

I thought System_file was only a mechanism to suppress a few warnings. Evidently, it does more.

**Comment by erkyrath** [comment]
In the earliest incarnation of `Replace` (as described in the DM4), the *only* valid use was to replace a function appearing in a System_file. The `Replace` directive had to appear before the System_file `Include`, and (I think) before any usage of the function name.

I've made it somewhat more general, in that you can now `Replace` functions which are not in a System_file. However, it still treats System_file specially, and for backwards-compatibility reasons it always will.
