### ISSUE TITLE
Failure related to switch/case handling when compiling with library 6/12

### ISSUE THREAD

**Issue by cfmoorz2** [DavidKinder/Inform6#231]
just comiled the latest

i get this error message:

charlesmoore@Charless-MacBook-Pro IF % inform6_4 -w main
Inform 6.42 (in development)
"Verblib.h", line 1081: Error:  Expected name of action but found Look
>       0:    <Look
Compiled with 1 error and 13 suppressed warnings (no output)

i am using most current library files and have made no changes to them.

works fine with 6.34

**Comment by erkyrath** [comment]
Yeah, I can replicate this. It's some kind of follow-on to https://github.com/DavidKinder/Inform6/pull/214 -- I clearly didn't test enough cases.

You should switch back to 6.41 until I figure this out.

**Comment by erkyrath** [comment]
Short test case:

```
[ Main;
	testfunc();
];

[ LookSub; ];

[ testfunc val;
	switch (val) {
		0: <Look>;
	}
];
```

**Comment by erkyrath** [comment]
(And I should add a library 6/12 test case to the test suite...)
