### ISSUE TITLE
Marking long dictionary words as plural doesn't work

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#244]
When compiling to v3, the compiler (v6.41) fails to give 'shelves//p' the plural flag. 

When compiling to v3 or v5, the compiler fails to give 'superstructures//p' the plural flag. 

I'm guessing that it stops processing the word after six characters, and so it misses the "//p" part.

```
Array foo table
	'shelf'
	'shelves//p'
	'scone'
	'scones//p'
	'house'
	'houses//p'
	'arm'
	'arms//p'
	'superstructures//p';

[ TestPlural p_word;
	print (address) p_word;
	if((p_word -> #dict_par1) & 4)
		print " [PLURAL]";
	new_line;
];

[ main i;
	print "Under v3, the compiler fails to mark 'shelves//p' as plural.^^";
	print "Under both v3 and v5, the compiler fails to mark 'superstructures//p' as plural.^^";
	for(i=1: i<=foo-->0: i++)
		TestPlural(foo-->i);
];
```

**Comment by erkyrath** [comment]
> I'm guessing that it stops processing the word after six characters, and so it misses the "//p" part.

Yeah, that's what I see. If the "//p" starts after character 9 (char 6 for v3), it's not recognized. The code for Glulx is similar, stopping at DICT_WORD_SIZE.

This isn't necessarily a bug but it's unintuitive. Probably worth changing so that the `//p` is recognized at the end, no matter how long the word is.

**Comment by erkyrath** [comment]
Note to self: change error message (both Z and G) to

> Expected ‘p’ after ‘//’ in dict word (plural flag)

**Comment by erkyrath** [comment]
Historical note: reported long ago as https://www.inform-fiction.org/patches/C62103.html . That says "fixed in 6.30" but I guess not.

**Comment by erkyrath** [comment]
(I've passed this question over to Graham.)

**Comment by erkyrath** [comment]
This has been idling for a month. I'm just going to go with the `$LONG_DICT_FLAG_FIX` option.
