### ISSUE TITLE
container/surface bug, look code gets called twice?

### ISSUE THREAD

**Issue by cfmoorz2** [DavidKinder/Inform6#250]
compile the attached test file for details but there is a bug when the player is in/on a container or supporter with other objects. the code to iterate through objects/siblings is getting called twice. 

in the test room, 'stand on the surface', then 'drop all', then 'look'. 

[test.txt](https://github.com/DavidKinder/Inform6/files/12707396/test.txt)

**Comment by erkyrath** [comment]
That's a library bug. Report those here: https://gitlab.com/DavidGriffith/inform6lib/-/issues
