### ISSUE TITLE
Overly long name array corrupts object in z3

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#27]
An object which has a name array longer than 4 dictionary words raises a warning when compiled to z3, and the compiler says it will truncate the array. But the object ends up corrupted.

This object:

Object ->  Surfaceofthewater "Atlantic Ocean"
  with  name 'Surface' 'of' 'the' 'water', 'ocean', 'atlantic' 'ocean' 'sea' 'seawater' 'waves',
        description "TODO",
        before [; Enter: print "You enter the ocean...^"; <Go FAKE_S_OBJ>; rtrue;
        ];

Ended up like this in the story file (output from ztools/infodump):

 13. Attributes: None
     Parent object:  10  Sibling object:  14  Child object:   0
     Property address: 0be9
         Description: "Atlantic Ocean"
          Properties:
              [20] 44 59 
              [ 4] 39 a5 
              [ 1] 33 5b 30 3d 
              [19] b6 34 
              [18] 30 36 2a a9 30 36 
              [18] 6d 32 
              [27] 34 b9 00 0e 
              [19] 34 
              [20] 14 2c 7e 
              [ 6] 9c 2a e0 1a 
              [20] 4d 83 7b 
              [23] 29 58 
              [ 1] cb 
              [ 1] 2a 
              [23] 2d 00 05 
              [ 4] a5 34 44 72 21 33 
              [28] 30 3d 33 b6 34 11 2a 5c 
              [19] b6 34 
              [ 6] 2e a0 
              [12] 9a 00 
              [ 2] 13 
              [13] 8b 
              [ 5] 00 80 

Property 20 get three different values. Some property values have length 1 or 3, something I believe the Inform compiler should never do.

Used Inform 6.34, the binary for Win32 available at if-archive, with the PunyInfom library.

**Comment by fredrikr** [comment]
Seems to me that this is fixed by changing line 1265 in objects.c from:

                full_object.pp[next_prop].l=4;

to:

                length = 8;

I tested this and the object isn't corrupted.

(Tried to make a PR but failed miserably. Don't know if I lack the rights or the knowledge.)

**Comment by erkyrath** [comment]
No problem. For a one-line change, a PR doesn't save any time.

I'll take a look at this soon.
