### ISSUE TITLE
Add `$IGNORE_INLINE_COMPILER_SETTINGS` compiler setting

### ISSUE THREAD

**Issue by heasm66** [DavidKinder/Inform6#275]
only use options specified at command line, ignore definitions (inside story-file) of `DEBUG`,` Grammar__Version`, all` !%` definitions, and maybe a few more. As of now I think last defined gets precendence, but in my mind at least it is a bit unclear what will happen when there’s a conflict.

`-i` doesn't do this, does it? Could be an option otherwise.

**Comment by erkyrath** [comment]
This option seems like it would only add to the confusion.

The precedence is currently:

- inside-story-file declarations  (highest)
- `!%` lines
-  command-line options and ICL files, in order as they're parsed on the command line.

It would be more intuitive if command-line options took precedence over `!%` lines and everything else. However, the way Inform parsing is set up, this would be ugly to implement.

**Comment by DavidKinder** [comment]
Closing this as if we do something here, it probably will be https://github.com/DavidKinder/Inform6/issues/279.
