### ISSUE TITLE
Error in $GRAMMAR_META_FLAG documentation

### ISSUE THREAD

**Issue by auraes** [DavidKinder/Inform6#298]
In ReleaseNotes.html about A new setting $GRAMMAR_META_FLAG, we read :

>  Previously, meta actions were defined by writing lines like
> `Verb 'score' * -> Score meta;`

 instead of 
`Verb meta 'score' * -> Score;`

**Comment by DavidKinder** [comment]
Fixed in commit 28c2ffb259a27112df74458e0fa61f3369f556e4.
