### ISSUE TITLE
The recording of unicode text (gametext.txt) is altered if an accent is present in a dictionary word

### ISSUE THREAD

**Issue by auraes** [DavidKinder/Inform6#299]
In the first case, there's no accent on the dictionary word: foret; in the second, there is one: forêt.
I don't know if this is due to my text editor and/or my terminal configuration (Linux UTF-8) or other reasons.
```
!% -Cu
Dictionary 'foret';
!Dictionary 'forêt';
[ Main;
    print "à â ä ç é è ê ë î ï ô ö ù û ü ÿ œ æ « » À Â Ä Ç É È Ê Ë Î Ï Ô Ö Ù Û Ü Œ Æ";
];
```
gametext.txt:
> Transcript of the text of "test.inf"
> [From Inform 6.43 (in development)]
> 
> à â ä ç é è ê ë î ï ô ö ù û ü ÿ œ æ « » À Â Ä Ç É È Ê Ë Î Ï Ô Ö Ù Û Ü Œ Æ
> 
> [Dictionary contains 1 entries:]
> foret        
> 
> [Compiled Z-machine version 5]
> [End of transcript: release 1, serial 240807]

```
!% -Cu
!Dictionary 'foret';
Dictionary 'forêt';
[ Main;
    print "à â ä ç é è ê ë î ï ô ö ù û ü ÿ œ æ « » À Â Ä Ç É È Ê Ë Î Ï Ô Ö Ù Û Ü Œ Æ";
];
```
gametext.txt:
> Transcript of the text of "test.inf"
> [From Inform 6.43 (in development)]
> 
> Ã  Ã¢ Ã¤ Ã§ Ã© Ã¨ Ãª Ã« Ã® Ã¯ Ã´ Ã¶ Ã¹ Ã» Ã¼ Ã¿ Å Ã¦ Â« Â» Ã Ã Ã Ã Ã Ã Ã Ã Ã Ã Ã Ã Ã Ã Ã Å Ã
> 
> [Dictionary contains 1 entries:]
> forêt        
> 
> [Compiled Z-machine version 5]
> [End of transcript: release 1, serial 240807]

```

**Comment by erkyrath** [comment]
The dictionary word is being printed wrong (Latin-1 rather than UTF8). This then confuses your terminal, which prints the entire file as Latin-1. The game text part of the output is correct, though.

**Comment by erkyrath** [comment]
Bug does not occur if `-G` and `DICT_CHAR_SIZE=4`.

**Comment by erkyrath** [comment]
While we're at it, the `--trace dict` output has the same problem.

**Comment by erkyrath** [comment]
Fixed by https://github.com/DavidKinder/Inform6/pull/300 .
