### ISSUE TITLE
Allow default language to be specified at compile time

### ISSUE THREAD

**Issue by DavidGriffith** [DavidKinder/Inform6#30]
It would be handy if the default language could be specified at compile time.  Currently this is hardcoded here: https://github.com/DavidKinder/Inform6/blob/077038cf177a2ae972846b8a3f5da2081df96710/inform.c#L591. 

I'd do this by adding something like `Default_Language` to be checked in the same fashion as is done here:
https://github.com/DavidKinder/Inform6/blob/077038cf177a2ae972846b8a3f5da2081df96710/inform.c#L584

However, if `Default_Language` is undefined, then `English` would be used instead.

My reason for this is that capitalization forces some gyrations with symlinks in a Unix environment to get things compiled.  In https://gitlab.com/DavidGriffith/inform6unix I'm dealing with this by applying a patch to the Inform6 compiler code before compiling.

**Comment by erkyrath** [comment]
So have a stanza in the header.h that's roughly this?

#ifndef Default_Language
#define Default_Language "English"
#endif

Seems reasonable.

**Comment by DavidGriffith** [comment]
Exactly.  I'd like to prepare and submit a PR to do this.

**Comment by erkyrath** [comment]
Go for it. I'll look it over when it's up.

**Comment by erkyrath** [comment]
I've adjusted your PR slightly and made a new one: https://github.com/DavidKinder/Inform6/pull/32

I moved the new stanza to a more consistent place in header.h. Also updated inform.c to make use of the new #define.

**Comment by DavidGriffith** [comment]
> I've adjusted your PR slightly and made a new one: #32
> 
> I moved the new stanza to a more consistent place in header.h. Also updated inform.c to make use of the new #define.

Whoops.  That was embarrassing to forget editing inform.c
