### ISSUE TITLE
Compiler doesn't complain about too many objects

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#304]
A z3 file can have no more than 255 objects, but the compiler will produce a Z-code file without showing an error message even if more objects than that are defined.

![image](https://github.com/user-attachments/assets/b9333e24-2836-43e9-88a4-9a5e3a0b2486)

**Comment by erkyrath** [comment]
It's quite possible that the MAX_OBJECTS setting used to handle this check, and I accidentally nerfed it when I took out the settings. Oops.

**Comment by erkyrath** [comment]
For the record, no, this limit was never checked.
