### ISSUE TITLE
ZCODE_COMPACT_GLOBALS, only allocate space for actually used globals

### ISSUE THREAD

**Issue by heasm66** [DavidKinder/Inform6#306]
Premise: If not all globals are used it would be possible to move up the arrays and start that section directly after the last used global. There's precedence for this, for example, look at *Hitchhiker's Guide, r31, 871119 (Solid Gold)* that only use 364, istead of 480, bytes for the globals.
```
***** MEMORY MAP *****

00000-03B33 DYNAMIC MEMORY
   00000-0003F Header table, 64 bytes.
   00040-001FF Abbreviation strings, 448 bytes.
   00200-002BF Abbreviation table, 192 bytes.
   002C0-0042B Global variables, 364 bytes.
   0042C-004A9 Object defaults table, 126 bytes.
   004AA-01191 Object tree table, 3,304 bytes.
   01192-02970 Object properties tables, 6,111 bytes.
   02971-03B33 Unidentified data, 4,547 bytes.

03B34-06E78 STATIC MEMORY
   03B34-03C51 Syntax/Grammar table, 286 bytes.
   03C52-04760 Syntax/Grammar table data, 2,831 bytes.
   04761-048CE Action table, 366 bytes.
   048CF-04A3C Preaction table, 366 bytes.
   04A3D-04A9E Preposition/Adjective table, 98 bytes.
   04A9F-06E78 Vocabulary/Dictionary, 9,178 bytes.

06E79-26ACB HIGH MEMORY
   06E79-070BF Unidentified data, 583 bytes.
   070C0-1C64B Z-code, 87,436 bytes.
   1C64C-26ACB Static strings, 42,112 bytes.
```
To achieve this we need to move the Inform scratch variables from globals 234-240 to some other place, introduce a new setting, move up the arrays and adjusting the backpatching values.

I have a branch that does this in three steps, https://github.com/heasm66/Inform6/tree/compact_globals

### Step 1: Add ZCODE_COMPACT_GLOBALS setting
`ZCODE_COMPACT_GLOBALS=0` produces identical bytecode as before, `ZCODE_COMPACT_GLOBALS=1` move up the arrays to start immediately after last used global.
(Commit: https://github.com/heasm66/Inform6/commit/56e09ce737247a8440ff4dc85ffbd47da4bc4ab2)

### Step 2: Remove hard-coded values for scratch globals
Currently Inform6 have a couple of places where the values for the scratch variables are hard coded (249-255). Change this by introducing a couple of global int:s that hold the places for the variables, depending on the setting of `ZCODE_COMPACT_GLOBALS`.
```
    ZCODE_COMPACT_GLOBALS=0             : Scratch variables are at 234-240 as before.
    ZCODE_COMPACT_GLOBALS=1, version 1-3: Scratch variables are at 4-10 (globals 1-3 are used by 
                                          interpreters to read location, score and moves for the statusline).
    ZCODE_COMPACT_GLOBALS=1, version 5+ : Scratch variables are at 1-7.
```
(Commit: https://github.com/heasm66/Inform6/commit/8def8044892d673dda864e3d26dfc2ca8eb2ba19 and https://github.com/heasm66/Inform6/commit/743e483bb4bc069e16a7232adbfcabcd59063b0b)

### Step 3: Compact globals by moving arrays up and adjusting backpatching
Pretty much starting the arrays directly after last used global, instead of filling out to 480 bytes. We also need an adjustement value to apply to all backpatching of arrays because they initally are calculated to start at `variables_offset+480`.
(Commit: https://github.com/heasm66/Inform6/commit/2649ccf5ceaa62ea79c89f6b49fcae22593d3ba8)

**Comment by erkyrath** [comment]
Thanks for working on this!

I haven't looked at your branch, but it seems like a reasonable idea. Having to swizzle the globals around is unfortunate but it shouldn't add too much complication.

I said a while ago that I wanted to leave the main branch mostly frozen until the next I7 release. (We were dealing with a sequence of changes to the verb code, both for GV3 and for I7 reasons, and instability seemed like a bad idea.)

The I7 release has been slower than I'd hoped, obviously. I still want to stay hands-off for the optimization branch. But this change is opt-in and Z-only, so it should be okay to accept.

I'll try to look over your branch this week.

**Comment by heasm66** [comment]
Thank you!

One way to avoid the "swizzle" of the scratch globals would be to permanently store them in position 4-10 and use the solution for version 3 for all versions.

**Comment by erkyrath** [comment]
That would unnecessarily change existing behavior, which is a serious no-no for this project. See above about "opt-in".

**Comment by heasm66** [comment]
Ooh, I only meant for the "opt-in" to do the same for all versions, without it they should remain as the last 7 globals.

**Comment by erkyrath** [comment]
You know, this makes the source _easier_ to read in some places. Fewer hardcoded numeric constants.

I have a branch based on yours: https://github.com/erkyrath/Inform6/tree/compact_globals

However, I haven't fully tested it yet.

**Comment by erkyrath** [comment]
When testing this setup with frotz, it works fine. However, in bocfel (and gargoyle), it fails in both z3 and z5:

> [Fatal error: corrupted story: global variables are not in dynamic memory]

**Comment by heasm66** [comment]
Hmm... I know that Zilf regulary compact the globals.

Looking at the code in Bocfel (ver 2.2.2) that throws the error(`zterp.cpp..process_story`).
```
    if (header.globals < 64 || header.globals + 480UL > header.static_start) {
        die("corrupted story: global variables are not in dynamic memory");
    }
```
I suspect that if the story don't contains enough arrays to fill up the hardcoded assumed size for the globals, this error willl be thrown.

**Comment by heasm66** [comment]
Confirmed.
```
global score 0;
global moves 0;
global locvation 0;

[Main;
    "Hello World!";
];
```
Throws `[Fatal error: corrupted story: global variables are not in dynamic memory]`
```
global score 0;
global moves 0;
global locvation 0;

array padding-->480;

[Main;
    "Hello World!";
];
```
Runs fine.

Real life stories most probably have enough arrays for this not to pop up. Maybe report it as an issue to Bocfel and have a note in the release notes?

**Comment by erkyrath** [comment]
We'd need a pretty serious warning for an option that's known to fail on some interpreters.

However, I said that the I6 compiler should be able to push the boundaries of unsupported code if the author wants. I guess this fits that category. `:)`

**Comment by heasm66** [comment]
We could add a warning somewhere in `construct_storyfile_z`, something like:
```
    if ((static_memory_offset - variables_offset) < 480)
        warning("Not enough space for 240 globals in dynamic memory may cause error in some interpreters.");
```

**Comment by curiousdannii** [comment]
@cspiegel do you remember why you wrote Bocfel to have a minimum globals limit of 64?

**Comment by erkyrath** [comment]
It's a reasonable reading of the standard. Just not one that Infocom always followed.

I'd like to take this to the forum, actually, just to make sure everybody is aware of the situation.

**Comment by curiousdannii** [comment]
Oh wait, it's not about the number of globals, it's the address.

6.2 says that the globals are in dynamic memory, so the second part of the check is valid.

But 1.1 says that dynamic memory must only be at least 64 bytes.

1.1.1.1 says in general the header shouldn't be written to. Which kind of implies the header shouldn't overlap with the globals.

**Comment by erkyrath** [comment]
Forum thread: https://intfiction.org/t/squashed-globals-in-z-code/72785

**Comment by erkyrath** [comment]
Strong forum concensus that if that happens (few globals, small array space) we should nudge up the start of static memory so that it's at least 480 bytes past the start of globals. I've added that check.

There's one more corner case: in v3, if the game defines fewer than three globals, we never reserve space for the built-ins (which come _after_ the first three user globals). Then arrays collide with temp_global, sw__var, etc.

Gonna have to enforce a minimum of 10 globals in v3 ZCODE_COMPACT_GLOBALS mode.
