### ISSUE TITLE
Ifdef doesn't work at the start of a switch block

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#35]
This gives an error:

`
Constant PRINT_WARNING;

[Initialise x;
	x = 1;
	switch(x) {
#IfDef PRINT_WARNING;
		1: print "1!^";
#Endif;
		default: print "Other^";
	}
	print "End.^";
];
`

But if you add `		0: print "0!^";` just before #ifdef, it works.

**Comment by erkyrath** [comment]
Error message:

    line 26: Error:  Expected switch value but found #
    > #IfDef

**Comment by erkyrath** [comment]
The error occurs in parse_code_block(). 

What needs to happen is to explicitly check for a hash-directive:

    if ((token_type == SEP_TT) && (token_value == HASH_SEP)) ...

and then call parse_directive(TRUE). However, it will take some digging to figure out the right place to do that.

(This will require a whole lot of regression test.)
