### ISSUE TITLE
Extra copies of dictionary words in z3

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#36]
If you compile a game to z3, and there are two dictionary words in the source code which are not different with the six-character resolution of z3, but would be different if the resolution was 9 characters as in z5, they are created as separate dictionary words, which causes all sorts of problems. Example:

Object Scorpion "scorpion"
	with
		name 'scorpionx' 'scorpiony';

This creates two dictionary words: 'scorpi' and 'scorpi' (truncated to six characters). Depending on the interpreter's method of searching the dictionary, one or the other may be matched when the player type a word beginning with scorpi.

**Comment by erkyrath** [comment]
I think the fix would be to add a version_number check to the line 

    if (i>=9) break;

...in dictionary_prepare_z()?
