### ISSUE TITLE
AfterGameOver "RESTART" option doesn't call LibraryMessages

### ISSUE THREAD

**Issue by sarashinai** [DavidKinder/Inform6#46]
I have created thus
```
Object LibraryMessages
    with before [;
        Restart:
            print "Are you sure you want to restart? ";

            if (YesOrNo()){
               JSCommunication.RunCode("gameConsole.makeInformCall('Main', 'restart');");
            }     

            return true;
    ]
;
```
Which works reasonably well for overriding the restart command issued to the prompt.

However, the RESTART option provided in AfterGameOver (parser.h, line 5441), circumvents this. I have "corrected" this by changing line 5469 to `if (~L__M(##Restart) == false) @restart;` but I suspect this is not the correct overall solution.

**Comment by DavidKinder** [comment]
This project is only for the compiler: the Inform 6 library is now a separate project at https://gitlab.com/DavidGriffith/inform6lib

**Comment by sarashinai** [comment]
Quite right, apologies!
