### ISSUE TITLE
ifdef limitation

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#48]
Not sure how fixable this is, but it's a bit annoying and it can also lead to code compiled but not working as intended.

This doesn't compile:

```
[main a b;
#Ifdef FOO;
	if(a == b) print "Yes";
#Ifnot;
	if(a < b) print "Yes";
#Endif;
	else print "No";
];
```

By the time the compiler gets to "else" it doesn't remember the "if" context.

The following program compiles but it doesn't work as intended:

```
[main a b;
#Ifdef FOO;
	if(a == b)
#Ifnot;
	if(a < b)
#Endif;
 		print "Yes";
	print "Press a key: ";
	@read_char b;
];
```

print "Yes"; is performed regardless of the condition.

**Comment by erkyrath** [comment]
I *think* this is easy to fix, by adding an extra directive check in the IF_CODE block in states.c. Well. "Easy" in some abstract sense.

Closely related to https://github.com/DavidKinder/Inform6/issues/35 , which I'm sure you'll remember... Like that one, this change will require a lot of regression testing.
