### ISSUE TITLE
Broken Iftrue?

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#50]
This doesn't compile:

```
Constant FOO "String";

Default FOO 5;

[ Test;
#IfTrue FOO < 10;
	print "Hello^";
#EndIf;
	print "Goodbye^";
];

[main b;
	Test();
	@read_char b;
];
```

Is it that the value of FOO isn't known on the first pass, since the compiler can't know the final address of the string until it has compiled the code?

This is a pattern we use in PunyInform for replacing library messages, and no one has complained that it doesn't work yet, but maybe they haven't tried it just this way.

**Comment by erkyrath** [comment]
(Please include the error message when reporting a compile failure.)

> line 10: Error:  Expected constant but found <expression>

You're right, the compiler can't determine string addresses at the point where "FOO < 10" is being evaluated. You'll note that it works fine if FOO is defined as a number. Also, the Default line is irrelevant here.

**Comment by fredrikr** [comment]
Sorry, I meant to include the error message.

Ok, time for some rethinking for us then. Thanks for lookng into it.

**Comment by fredrikr** [comment]
Is there a way to check if a constant has a value that can be compared using #if statements? (To work around this issue)

**Comment by erkyrath** [comment]
No, I don't think so. 

Does it make sense to structure your code so that you're checking `#ifdef` rather than comparing the constant value?

**Comment by fredrikr** [comment]
I can't see how. Either PunyInform has defined the value, or the game author has. We need to tell the difference.

This is how it currently works: Each constant is a library message, and each constant can be either:

* a number in the range 1-1000, meaning it's a complex message (a message that has a piece of code to print it) and it has its original definition
* a number in the range 1000-1299, meaning it's a complex message that the game author has chosen to replace, so there is code in the game's own library message routine to print it.
* a string address, meaning it's a simple string to be printed.

If we detect that the game has created a string or a complex message number (1000-1299) to replace a message, we don't want to include the original message in the compilation, since it won't be printed anyway. This currently works if it's been set to a complex message number, but not if it's been set to a string.

This is what the library file looks like: https://github.com/johanberntsson/PunyInform/blob/master/lib/messages.h

**Comment by erkyrath** [comment]
I don't entirely get that. I think that what you're trying to do is use the `#if` directives to optimize out strings and code that the author has replaced. While also keeping all the code (your "complex messages") in a single routine, rather than broken out into separate routines.

I see why you'd want that. However, I don't think Inform is powerful enough to handle that complex a scheme *and* optimize the way you want.
