### ISSUE TITLE
`remove_temp_files` & `unlink_temp_files`

### ISSUE THREAD

**Issue by Kroc** [DavidKinder/Inform6#52]
I'm trying to compile the current commit of Inform6 for EPOC32 which limits me to VC6 and an ancient version of GCC that don't support C99. There weren't many problems! A few variables not defined at the beginning of a scope, and `snprintf` is missing, but I noticed something unusual that might not be related to C89/C99: "inform6.c" calls `remove_temp_files` from "files.c", but that function doesn't exist, only `unlink_temp_files`! This is easily fixed for me, but I wonder if this is supposed to be this way?

**Comment by erkyrath** [comment]
Are you sure you're looking at the current version? `remove_temp_files` is defined in files.c; there's no mention of `unlink_temp_files`. Also, there is no source file called `inform6.c`.

**Comment by Kroc** [comment]
My mistake with "inform6.c", that was a typo. I downloaded the current HEAD, but it appears I must have made a silly search/replace mistake, my bad. I can externally redefine the missing C99 functions, but could I submit a pull-request to you to move a handful of variable declarations to the top of their scope so that C89 works 'out of the box'?

**Comment by erkyrath** [comment]
Go ahead. I don't promise to remember to maintain this in future updates, though.

**Comment by Kroc** [comment]
Not really a problem; I just need to compile v6.34/5 for PunyInform use 👍
