### ISSUE TITLE
I think inform6 needs a Makefile, so I wrote one.

### ISSUE THREAD

**Issue by neroden** [DavidKinder/Inform6#57]
There are two reasons I think it should:
- Proper choice of compilation technique can have a significant effect on the speed of inform6 (this makes an inform6 nearly twice as fast as the one in Debian/Ubuntu)
- Being able to type "make" rather than invoking gcc directly is a lower-barrier-of-entry process for typical Linux users

This should of course be named Makefile when checked into the repo, but github wouldn't let me upload it under that name.

[Makefile.txt](https://github.com/DavidKinder/Inform6/files/6202190/Makefile.txt)

**Comment by erkyrath** [comment]
I am not particularly in favor. There's no reason to hardcode gcc (although Macs have clang symlinked to "gcc") and I don't know how universal the flto option is.

Also, people with a barrier to compiling code don't download and compile source code on Linux. A package manager person will wind up using David Griffith's "I6 for Linux" package, which comes with a Makefile and library source and installs them all in Linux-appropriate places.

**Comment by neroden** [comment]
* David Griffith's package is sufficiently obscure that I could not find it using Google until you printed his NAME, even then I had difficulty finding it, and I had not heard of it before now.

* I'm currently installing Inform 6.34 only as a substrate for Inform 7, so I don't need the other things in his package.

* However, I may try to contact him now that I know that he *exists*.  A 50% cut in program running time along with a smaller executable file is significant.

* Everything erkyrath said is wrong.  Literally all of it!

First of all, erkyrath doesn't know how to read a Makefile: gcc is not hardcoded (it's defaulted and can be overriden); the flto option isn't either (it's defaulted and can be overridden again).

Second, people with a barrier to compiling code do download and compile source code on Linux.  Not explaining how the code is supposed to be compiled is a barrier even for people who have downloaded and compiled code.  A README or HOWTO or something similar is normal in projects, and the lack of any instructions is a barrier.

Finally, the Debian package maintained by Ben Finney does not, in actual fact, use David Griffith's package.  It uses this one.  (You can check for yourself -- the package is inform6-compiler in the sid distribution).

**Comment by DavidKinder** [comment]
I do not believe that a makefile is needed and I am not intending to add one.
