### ISSUE TITLE
Clarify inform6 -h2 output regarding v7

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#65]
This is part of the output for inform6 -h2:

  v3  compile to version-3 ("Standard") story file
  v4  compile to version-4 ("Plus") story file
  v5  compile to version-5 ("Advanced") story file: the default
  v6  compile to version-6 (graphical) story file
  v8  compile to version-8 (expanded "Advanced") story file
...
  B   use big memory model (for large V6/V7 files)
  
  So in essence there's no documented way to tell the compiler to build a v7 file, but if you do, -B might be useful.

**Comment by erkyrath** [comment]
You're right, that's an omission. -h1 mentions v7 but -h2 doesn't.

**Comment by DavidKinder** [comment]
V7 isn't really "alternate graphical", though, is it? My recollection is that it's just V5 with the V6 way of packing addresses.

**Comment by fredrikr** [comment]
There's nothing graphical about it, no. Like V5 with the V6 way of packing addresses is a correct description, AFAIK.

**Comment by erkyrath** [comment]
Right, thanks. I was just remembering it wrong.
