### ISSUE TITLE
Release tags, anyone?

### ISSUE THREAD

**Issue by SamB** [DavidKinder/Inform6#7]
You seem to have made some releases without tagging any of them.  This makes archaeology, or even just figuring out what's been changed since the latest release, tricky.

**Comment by akien-mga** [comment]
It would still be useful to have the tags in this repository and not in a fork. Tags are easy to make a push, this script should do the trick:
```
git checkout  f45ee9b && git tag v6.32
git checkout c47da62 && git tag v6.31N-3
git checkout 50c1420 && git tag v6.31N-2
git checkout aa52d37 && git tag v6.31N
git checkout 9a128aa && git tag v6.31
git checkout ea366aa && git tag v6.30
git push --tags
```
