### ISSUE TITLE
Stop automatically setting -D when you set -k?

### ISSUE THREAD

**Issue by curiousdannii** [DavidKinder/Inform6#72]
I was trying to compile Glulxercise with the `-k` option, and Inform gives this error:

```
"<constructing output>", line 0: Error:  No such constant as "debug_flag"
```

This seems to come from the veneer's use of `debug_flag`.

I don't know what the best thing to do is, but this feels quite nonoptimal to me.

Would it be possible to insert this code if the `-k` flag is used?

```
#ifndef debug_flag;
Global debug_flag = 0;
#endif;
```

I've added this to Glulxercise and it now compiles, but it says that `debug_flag` isn't used, so I guess it's not detecting its use by the veneer?

**Comment by erkyrath** [comment]
I remember some discussion about this on the forum, lemme look...

https://intfiction.org/t/inform-6-error-when-compiling-with-d-without-the-library/45889

I guess no bug ever got filed. (Or maybe it was filed on the old mantis tracker, sigh.)

Glulxercise has no debug features, so adding code to support DEBUG mode seems pointless. If what you're looking for is the gameinfo.dbg file, you can do this:

    inform -G -k -~D glulxercise.inf

Maybe -k doesn't need to turn on -D any more? I was surprised that it does. I7 sets both flags explicitly, so changing this behavior shouldn't cause problems.

**Comment by curiousdannii** [comment]
Thanks for the tip of using `-~D`.

Disconnecting `-k` and `-D` makes sense to me. Maybe the help description for `-k` could also be changed to not refer to Infix anymore, as that's not really relevant to the xml file?
