### ISSUE TITLE
Selecting desired library

### ISSUE THREAD

**Issue by DavidGriffith** [DavidKinder/Inform6#79]
Over at https://gitlab.com/DavidGriffith/inform6unix I'm experimenting with the idea of being able to select which library the author wants to use with a minimum of hassle.  I've worked out a scheme that seems to work by requiring the use of a Makefile or else requiring the author to type in a long override of `Include_Path` by way of the `+dir` flag.  I'd like to be able to do `inform -L std foo.inf` to compile something using the Standard library and `inform -L puny bar.inf` to use PunyInform.  This would easily extend for any number of alternate libraries.

I envision this happening by reworking the `*_path` parameters that are compiled into the compiler.  For instance, have `lib_path` contain `/usr/local/share/inform/lib`.  Then in `/usr/local/share/inform/lib` would go subdirectories for whatever libraries desired.  The `-L` flag would select what subdirectory to choose.  So `-L std` would include files from `/usr/local/share/inform/lib/std`.  Includes would be the same way: `/usr/local/share/inform/include/std` and so on because the includes mostly seem very library-specific.

How does this sound, at least in concept?

**Comment by Kroc** [comment]
Perhaps the same effect can be achieved by having two stub story files that each include a different library, and then include the real story file? For example: the `std.inf` file includes the standard library, and then includes `story.inf` and another file `puny.inf` include PunyInform and then includes `story.inf`.

Another possibility is using the recently added feature for defining symbols from the command-line, so that the story file can read from the command-line which library to include. I don't feel there is a need to add more code to the compiler to achieve what you need.

**Comment by erkyrath** [comment]
Swapping out the library for a given game doesn't seem like such a common request that we need to provide shortcuts for it. Different Inform libraries usually have different features (even between 6/11 and 6/12, e.g.) so most games will stick to one. For that, you can put a +path command in a header comment.

You might want to run the same code against different libraries in a test framework, but a test framework will automate everything, including any necessary +path commands.

**Comment by erkyrath** [comment]
> Another possibility is using the recently added feature for defining symbols from the command-line, so that the story file can read from the command-line which library to include.

I don't think this particular approach will work, though. You can put #ifdefs around Include commands, but selecting a different library usually means a different library *path*.

**Comment by DavidGriffith** [comment]
Having the author put a +path command in a header comment would be messy because it's a path.  It's not portable and would confuse authors not intimately aware of where the libraries are installed.  To get around this, I'm exploring the idea of an Inform6 preprocessor.

This is the basic patter: The Inform6 executable is renamed to something like `inform-compiler` and the preprocessor is named `inform`.  When the preprocessor is invoked, it runs `inform-compiler -h1` to discover the default `include_path`, then it chews through `foo.inf`, recursing along the way and ignoring what's not found.  If something included isn't found, we assume it's a library file that we can't find yet and we don't want to preprocess that anyway.  A preprocessor directive is in the form of `Constant LibraryName "puny";` for instance to select the library name.  Once the library name is known, a `+include_path=` can be constructed using what the preprocessor was told upon installation where the Inform6 libraries are (ie, `/usr/local/share/inform/`) and then `+include_path=/usr/local/share/inform/puny` can be passed to the compiler.  Other directives can be used to select a particular version of a library.  Then the compiler is executed using the arguments supplied to the preprocessor.  At all times, the author can just pretend the preprocessor doesn't exit and the magic just happens.

None of this really requires any cooperation with the compiler except for making sure that the format of where `include_path`'s current setting is shown doesn't change.  The compiler could look for the preprocessor, execute it first, and then continue, but that's not strictly necessary.

What do you think?

**Comment by erkyrath** [comment]
If you're going to run a separate program beforehand to set up the compiler arguments, why not use a Makefile? Or a two-line shell script? Or the already-supported `inform +/usr/local/share/inform/puny` ?

I still don't see a use case for this feature. No plausible game will compile correctly with both Puny and 6/12.

**Comment by Kroc** [comment]
Separate executables would be a roadblock for some ports, particularly WASM/emscriptem and in particular my EPOC32 port because the OS is fully C++ and the C-runtime is kind of janky and would not work well with multiple executables.

I can see the need for running the pre-processor only for lexical analysis / outside optimisation / documentation. This should be achieved with a command-line switch as it is done with GCC.

**Comment by DavidGriffith** [comment]
For the time being, I think that having authors call `punyinform mygame.inf` to get things set up correctly will suffice.
