### ISSUE TITLE
Incorrect storage in dictionary?

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#81]
Compile this with Inform 6.34, using -v3

```
Array buffer -> 100;
Array parse -> 100;


Object Being "human-like being"
	with
		name 'human' 'human-like' 'being';

[ Main i;
	print "Contents of Being.name:^";
	for(i=0 : i < (Being.#name / 2) : i++)
		print i, ": ", Being.&name-->i, "^";
	buffer->0 = 80;
	parse->0 = 20;
	@sread buffer parse;
	print "Contents of parse buffer:^";
	for(i=0 : i < parse->1 : i++)
		print i, ": ", (parse+0)-->(2 * i + 1), "^";
	@sread buffer parse;

];
```

Then run this in Windows Frotz and type this input: "human human-like being".

Apparently, human and human-like make two different dictionary words when compiling, but they are the same word when Windows Frotz looks up the words the player typed in the dictionary. I tried this in Gargoyle (Bocfel) too, with the same result.

The way I read the Z-machine spec ( https://www.inform-fiction.org/zmachine/standards/z1point1/sect03.html#seven ): 
* 'human' should be stored as first 'h' 'u' 'm' 'a' 'n' and then Z-character 5 as padding
* 'human-like' should be stored as first 'h' 'u' 'm' 'a' 'n' and then Z-character 5 for shift (which should then be followed by Z-character 28 for '-' but that's truncated since we've run out of space)

So they should be identical as dictionary words, no?

**Comment by fredrikr** [comment]
Confirmed: 'human' and 'human-like' end up as two identical words in the dictionary.

![image](https://user-images.githubusercontent.com/1001548/117584800-395db380-b10f-11eb-8966-cdb164d04986.png)

**Comment by erkyrath** [comment]
Still happens in the current source. This is a simpler test case:

```
[ Main val;
	val = 'human';
	print val, " ", (address) val, "^";
	val = 'humanlike';
	print val, " ", (address) val, "^";
	val = 'human-';
	print val, " ", (address) val, "^";
	val = 'human+';
	print val, " ", (address) val, "^";
	val = 'human-like';
	print val, " ", (address) val, "^";
	val = 'human+like';
	print val, " ", (address) val, "^";
];
```

Output (v3):

```
1173 human
1194 humanl
1187 human
1180 human
1187 human
1180 human
```

I think the problem is that `-` is a multi-zchar character, which gets cut off in this case. The dictionary code doesn't handle this right in v3. But it does in v5+. I'll have to look closer at the dict code to see why.

**Comment by fredrikr** [comment]
Note that two dictionary words which are printed the same could (and should) still be different, as incomplete codes should be kept. I.e. I think 'abcö' and 'abc%' should be different even when everything is working.

**Comment by erkyrath** [comment]
I have a patch and a test case: https://github.com/erkyrath/Inform6-Testing/blob/master/src/dict-cutoff-v3test.inf

@fredrikr , could you take a look at that test file and make sure all the test lines make sense to you?

**Comment by erkyrath** [comment]
My patch is this branch: https://github.com/erkyrath/Inform6/tree/v3-dict-cutoff

It's a simple change, and I'm *pretty* sure it's right, but more eyes on the tests would be appreciated.

**Comment by fredrikr** [comment]
All the testcases look good.

What I would perhaps add is a few v5+ tests where the alphabet table has been altered to put some  regular characters in A1, so you can test that a word ending with Z-character 4 is considered different from one ending with Z-character 5.

**Comment by erkyrath** [comment]
For the record, the diagnosis of this bug is: 

In v3 only, if two dict words differ only in Z-characters 7-9 (the chars that are not stored in v3), the compiler would generate two dict entries containing the same word.

(When I worked on https://github.com/DavidKinder/Inform6/issues/36 , I only tested v3 dict words that differed in the first six characters.)

**Comment by fredrikr** [comment]
The new tests for v4+ look good.

I think the comment "! A four-byte character in the seventh place leaves zchar 6 followed by no bits" should say *eighth place*, no?

Also, I miss a test to check that a shift to A1 in the ninth position is different from a shift to A2, which they should be. Like:

test_different('abcdefgh$', 'abcdefgh_');

**Comment by DavidGriffith** [comment]
> The new tests for v4+ look good.
> 
> I think the comment "! A four-byte character in the seventh place leaves zchar 6 followed by no bits" should say _eighth place_, no?
> 
> Also, I miss a test to check that a shift to A1 in the ninth position is different from a shift to A2, which they should be. Like:
> 
> test_different('abcdefgh$', 'abcdefgh_');

You were able to get it working for V4?  I've been having trouble with even producing a V4 due to problems in the veneer.

**Comment by erkyrath** [comment]
I've fixed the comment and added some test lines. Thanks.

**Comment by erkyrath** [comment]
> You were able to get it working for V4?

V4 works but you need the Metro84 library. Or no library -- most of the tests in this repo don't include a library at all.
