### ISSUE TITLE
Wanted: Warnings for using objects and attributes incorrectly

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#83]
Inform 6 has some operators where the operator on the left hand side must be a valid object ID and/or the one on the right hand side must be an object ID, a property ID or an attribute ID. In a few cases, giving the wrong kind of entity raises a warning. I can see that these operators confuse a lot of newcomers to Inform 6, and even I made a stupid mistake in this area recently ( `if(player has necklace) ...` :) ). Wouldn't it be nice with warnings when using the wrong kind of entity for these operators? Like for `Lamp.light = true` or `if(Lamp provides light)` etc. Here's a program covering some of the cases, with comments for the ones that currently give a warning.

```
Property p1;
Property p2;
Property p3;
Property p4;
Property p5;
Property p6;

Attribute a1;
Attribute a2;
Attribute a3;
Attribute a4;
Attribute a5;
Attribute a6;

Object o1 "o1"
	with
		p1 1,
		p2 1,
		p3 1,
		p4 1,
		p5 1,
		p6 1,
	has a1 a2 a3 a4 a5 a6;

Object o2 "o2";

[main;
	if(o2 has o1) print "o2 has o1";
	if(o2 has p1) print "o2 has p1"; ! Warning: Property not qualified by object
	if(o2 provides o1) print "o2 provides o1";
	if(o2 provides a1) print "o2 provides a1";
	if(o2 in p1) print "o2 in p1"; ! Warning: Property not qualified by object
	if(o2 in a1) print "o2 in a1";

	if(p1 has a1) print "p1 has a1"; ! Warning: Property not qualified by object
	if(p1 provides p1) print "p1 provides p1"; ! Warning: Property not qualified by object
	if(p1 in o1) print "p1 in o1"; ! Warning: Property not qualified by object

	if(a1 has a1) print "a1 has a1";
	if(a1 provides p1) print "a1 provides p1";
	if(a1 in o1) print "a1 in o1";

	if(o1.o2) print "o1.o2 ~= 0";
	if(o1.a2) print "o1.a2 ~= 0";

	give o1 p1; ! Warning: This is not a declared Attribute: "p1", Bare property name found. "self.prop" intended?
	give o1 o2; ! Warning: This is not a declared Attribute: "o2"

	give a1 a2;
	give p1 a2; ! Warning: Bare property name found. "self.prop" intended?
];

```

**Comment by erkyrath** [comment]
This seems possible.

However, in general, we can't give warnings about forward-declared symbols. (Forward-declared symbols should *work* in all these cases, but we can't retroactively give warnings about improper usage when the symbol is later declared.)

Normal library usage declares properties and attributes up front, so that will be fine for most people.

**Comment by erkyrath** [comment]
This is wrapped, although there are certainly more opportunities for compile-time type checking.

**Comment by fredrikr** [comment]
Very nice, thank you! I will be sure to test this with the latest PunyInform version.
