### ISSUE TITLE
Undeclared constant not detected by the compiler

### ISSUE THREAD

**Issue by auraes** [DavidKinder/Inform6#84]
The compiler does not detect that the constants for the Dictionary directive are not declared. However, it assigns them a value.

```
Dictionary 'word' DICT_XXX DICT_YYY;
[ main;
   print ('word'->#dict_par1), "^";
   print ('word'->#dict_par3), "^";
];
```
```
162
35
```
(instead of 128, 0)

**Comment by erkyrath** [comment]
That is, if the constants DICT_XXX or DICT_YYY are not yet defined, the compiler silently generates an incorrect dictionary. It should throw an error: "a definite value must be given".

Probably just need to change

                    if (module_switch && (AO.marker != 0))

to

                    if (AO.marker != 0)

in a couple of places.

**Comment by erkyrath** [comment]
(Check other "definite value" errors, e.g. in the Release directive. They may have the same bug.)
