### ISSUE TITLE
Optimal abbreviation parsing

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Inform6#90]
Not creating the optimal abbreviation list, but applying abbreviations optimally to each string as it is compiled. This is the try_abbreviations_from() function. It could be improved. 

Code sample attached. This is Matt Russotto's C# implementation from this post: https://intfiction.org/t/highly-optimized-abbreviations-computed-efficiently/48753/46

[optimalparse.txt](https://github.com/DavidKinder/Inform6/files/6540862/optimalparse.txt)

This involves repeatingly measuring the cost of a string with different abbreviations in place. (Cost meaning "length in Z-chars.") We might need a cut-down clone of translate_text() to do this efficiently.

**Comment by hlabrand** [comment]
I might try to tackle this soonish, I think I found a way to do this. Am I correct in my understanding that I would only need to modify the text.c file, in the translate_text function, to change the lines 470 to 476? And that translate_text function takes one string of the text (as regular characters, not zchars) as an input? Thanks

**Comment by erkyrath** [comment]
You would modify the try_abbreviations_from() function (line 180). 

> And that translate_text function takes one string of the text (as regular characters, not zchars) as an input?

That's correct, but translate_text() writes to an array. For this task, you'd have to either write to a temporary array or make a copy of translate_text() which only counts (without writing).

**Comment by erkyrath** [comment]
This is done: https://github.com/DavidKinder/Inform6/pull/108
