### ISSUE TITLE
Remove temporary-file (-F1) option?

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Inform6#94]
(This is a tentative proposal, posted for discussion.)

The `-F1` option is essentially a cheapass implementation of virtual memory at the application level. It is entirely unneeded on modern machines. Removing it would simplify the code. It would also marginally speed up the compiler, since we could get rid of the transfer_to_temp_file()/transfer_to_zcode_area() wrappers in asm.c.

A survey on the forum (https://intfiction.org/t/question-about-inform-6-temporary-files-option/51101) turned up nobody who cares about this feature.

Nonethless, I hate removing features. We should probably ask around a larger audience before doing it. (Not that I'm sure how to reach a larger audience of I6 users! I suppose my blog / twitter / planet-if is the best bet.)

**Comment by erkyrath** [comment]
Here's an amusing question: should I also tear out all the options relating to temporary files? This includes:

- Temporary_Directory (config define in header)
- Temporary_Path (buffer for path option)
- The `+temporary_path` option for setting it
- INCLUDE_TASK_ID (config define in header)
- unique_task_id() (configurable function in header)

**Comment by DavidKinder** [comment]
I would vote yes to removing all those options.

**Comment by Kroc** [comment]
Ironically on the Psion, the RAM and disk are one and the same so a temporary file doesn't save any memory unless pointed to the CF card (on models that have a slot). I would need to test if compiling a large game exceeds RAM and would require a temporary file on card.

**Comment by Kroc** [comment]
Any large story files you can recommend to try compiling?

**Comment by erkyrath** [comment]
The typical scales to test for Z-code are "one-room I6 game", "Advent.inf", and "one-room I7 game". Anything past that is Glulx territory. (Bronze, then Kerkerkruip or Counterfeit Monkey for a really large test.)

**Comment by Kroc** [comment]
"Advent.inf" allocates a total of "838'576 bytes of memory". That's a tiny amount and way less than I thought it would. I think it's safe to remove the temp file option 👍

**Comment by erkyrath** [comment]
Thanks!

**Comment by DavidKinder** [comment]
Fixed by commit ff4d819a3beae4bd8445a486ac9817c6ccd6265a.
