### ISSUE TITLE
Remove module-linking (-M, -U) options?

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Inform6#95]
(This is a tentative proposal, posted for discussion.)

Module linking has not been in general use for a long time, if it ever was.

Linking was only ever supported for .z5. (The DM4 disclaims .z8 support. It might work with .z3/4/6, but I don't think that's been tested. It has definitely never been implemented for Glulx.) The only benefit is a minor speed improvement. The list of caveats in the DM4 (chapter 38) are daunting. Removing it would simplify the compiler code by a lot.

Nonethless, I hate removing features. We should probably ask around a larger audience before doing it. (Not that I'm sure how to reach a larger audience of I6 users! I suppose my blog / twitter / planet-if is the best bet.)

**Comment by Kroc** [comment]
I can only say that I intend to use this feature as it saves exactly 8 seconds per compile on the Psion (38MHz baby!) not having to recompile PunyInform each time. Yes the restrictions are there, but this is sufficient for quick iterative builds. That said, it would not inconvenience me if you removed the feature as the lack of shell-scripting on the Psion makes it impractical to use.

**Comment by erkyrath** [comment]
Thanks -- that's a useful data point.

**Comment by erkyrath** [comment]
Have you tested module linking with z3? I've only tested it with z5.

**Comment by Kroc** [comment]
You can't compile Puny as a module because of using `Defaults` (and probably a ton of other stuff), so it's not worth pursuing. Modularising my game isn't worth while because it's never going to get to an unreasonably large size, so I would say it's safer to remove the feature since it's not implemented completely enough to be useful.

**Comment by Kroc** [comment]
Well now the AIF people have revealed their magnum opus that takes 20 minutes (!) to compile you should ask them if they're able to modularise their story. IIRC you can only use modules with debug on though?

**Comment by DavidKinder** [comment]
That 20 minute compile was with Inform 7, though - from the screenshot of the task manager you could see that "ni" was the process taking all the time and memory, not "inform6".

**Comment by erkyrath** [comment]
I7 can't using linking anyway because ni generates a single monolithic I6 source file.

Even if you pulled out the template/parser code and pre-compiled it as a module, it wouldn't save significant time for this game, because that's only a tiny fraction of the bulk of the I6 code.

**Comment by DavidGriffith** [comment]
The Standard Library doesn't use modules after the 6/11 release.  I don't think PunyInform ever bothered with it.

**Comment by DavidKinder** [comment]
Implemented in https://github.com/DavidKinder/Inform6/pull/188
