### ISSUE TITLE
Make mode switch -u generate $MAX_ABBREVS abbreviations

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#97]
Switch -u would be more useful if it could find as many abbreviations as the current setting of $MAX_ABREVS.

**Comment by fredrikr** [comment]
There are better algorithms out there, but I'm sure the built-in tool to generate abbreviations will still see a lot of use as long as it works.

**Comment by erkyrath** [comment]
I took a look at the optimise_abbreviations() and it's kind of opaque, actually. `:(` There are several buffers allocated with hard-coded sizes. bestyet2 is the first one to change (64), but it's not at all clear whether bestyet, tlbtab, and sub_buffer need to be adjusted to match. Or how.

(sub_buffer does not seem to be used at all?)

**Comment by erkyrath** [comment]
(sub_buffer is gone. tlbtab can be made reallocable, rather than having a fixed size of MAX_TLBS.)
